### PR TITLE
hotfix/slash agent url

### LINKED ISSUE #105: [Bug] - Rogue TUI - Cannot insert `/` in Agent URL and Rogue Server URL
**Describe the bug**
The user cannot enter `/` in the Agent URL and the Rogue Server URL

**To Reproduce**
1. Open `rogue-tui`
2. Go to '/eval'
3. Try to manually enter `/` in the `Agent URL` field

1. Open `rogue-tui`
2. Go to '/settings'
3. Try to manually enter `/` in the `Rogue Server URL` field

**Expected behavior**
The `/` should be inserted into the text.

**Screenshots**

Image

Image

### PR DESCRIPTION
**Pull request by drorIvry**
- **Hotfix/auto updater bug (#56)**
- **Use clipboard from bubbletea instead of os binaries (#57)**
- **Hotfix | version bump & pre-commit -> lefthook (#58)**
- **feature/scrolling and wrapping issues (#59)**
- **Add code of conduct (#77)**
- **FIRE-659 | OSS files (#79)**
- **--wip-- [skip ci]**
- **feature/md rendferer v2 (#85)**
- **Update README.md (#87)**
- **Update license section in README (#89)**
- **Change license description in README**
- **Replace Elastic License with MIT License**
- **README Changes**
- **Hotfix | License changes (#90)**
- **Feature | Update discord link (#97)**
- **hotfix/paste agent url (#102)**
- **feature/refactor-versions (#88)**
- **wip**

## Type of Change

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📝 Documentation update
- [ ] 🎨 Code style/refactoring (no functional changes)
- [ ] 🧪 Test updates
- [ ] 🔧 Configuration/build changes

## Changes Made

- 
- 
- 

## Checklist

- [ ] I have read the [CONTRIBUTING.md](../CONTRIBUTING.md) guide
- [ ] My code follows the code style of this project (PEP 8, type hints, docstrings)
- [ ] I have run `uv run black .` to format my code
- [ ] I have run `uv run flake8 .` and fixed all issues
- [ ] I have run `uv run mypy --config-file .mypy.ini .` and addressed type checking issues
- [ ] I have run `uv run bandit -c .bandit.yaml -r .` for security checks
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have run `uv run pytest` and all tests pass
- [ ] I have manually tested my changes
- [ ] I have updated the documentation accordingly
- [ ] I have added/updated type hints for new/modified functions
- [ ] My changes generate no new warnings
- [ ] I have checked my code for security issues
- [ ] Any dependent changes have been merged and published

## Testing

**Test Configuration**:
- Python version:
- OS:
- Other relevant details:

**Test Steps**:
1. 
2. 
3. 

## Related Issues/PRs

- Fixes #
- Related to #
- Depends on #

---

fixes #105

### CODE REVIEW

File: packages/tui/internal/tui/app.go [hunk 1]
```diff
@@ -964,6 +964,32 @@ func (m Model) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
...
+			// Don't intercept "/" if we're editing text in NewEvaluationScreen
+			if m.currentScreen == NewEvaluationScreen && m.evalState != nil && m.evalState.currentField <= 1 {
+				// Handle "/" character directly in text fields
+				s := "/"
+				switch m.evalState.currentField {
+				case 0: // AgentURL
+					runes := []rune(m.evalState.AgentURL)
+					m.evalState.AgentURL = string(runes[:m.evalState.cursorPos]) + s + string(runes[m.evalState.cursorPos:])
+					m.evalState.cursorPos++
+				case 1: // JudgeModel
```
Comment (yuval-qf) [inline packages/tui/internal/tui/app.go:977]: should there also be one for the rogue server url?

Comment (drorIvry) [reply packages/tui/internal/tui/app.go:977]: the other If handles it

```
if m.currentScreen == ConfigurationScreen && m.configState != nil &&
				m.configState.IsEditing && m.configState.ActiveField == ConfigFieldServerURL
```

**Review by yuval-qf — APPROVED** [review]
